name: Terraform Checks

on:
  pull_request:
    branches: [ "main" ]

jobs:
  terraform-checks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
   
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Format Terraform script
      run: terraform fmt -check

    - name: Init Terraform
      run: terraform init
       
    - name: Validate Terraform script
      run: terraform validate

    - uses: terraform-linters/setup-tflint@v3
      with:
        tflint_version: latest
   
    - name: TFLint version
      run: tflint --version

    - name: Init TFLint
      run: tflint --init

    - name: Run TFLint
      run: tflint -f compact
   
    - name: Terraform Plan
      run: terraform plan
